### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by milkina** [Dashoshik/Course#7]
1. Неотформатировано
2. PhoneDemo - закомментированое  удалите.

**Comment by Dashoshik** [comment]
Исправлено.
Спасибо.

**Comment by milkina** [comment]
Phone неотформатирован.

**Comment by Dashoshik** [comment]
Отформатирован.

**Comment by milkina** [comment]
1. Добавьте всем конструкторам и методам модификаторы доступа.
2. Рекомендуется писать все конструкторы после объявления переменных. Перенесите их.
3. Инкремент для count должен выполняться при вызове любого конструктора.
4. Добавьте finalize для уменьшения count

**Comment by Dashoshik** [comment]
Добрый день.
Отформатирован.

**Comment by milkina** [comment]
Добавьте всем методам модификаторы доступа.

**Comment by Dashoshik** [comment]
всем методам добавила модификатор доступа public

**Comment by milkina** [comment]
Зыбыла метод getPhoneNumber.

Done.

**Comment by Dashoshik** [comment]
добавила
